### ISSUE TITLE
tempcase not running on Windows

### ISSUE THREAD

**Issue by jasperoosthoek** [clbarnes/tempcase#1]
Currently, tempcase cannot create temporary directories in Windows. The created directory name uses `datetime.now().isoformat()` which inserts a colon (:) and this is not allowed.

I suggest adding these lines either before the class or something similar in the path_to_cls function:
```
if os.name == 'nt':
    TIMESTAMP = TIMESTAMP.replace(':', '_')
```

Regards, Jasper

**Comment by clbarnes** [comment]
Thanks for bringing this up! I should be able to get to this today.

**Comment by jasperoosthoek** [comment]
Great, thank you!

**Comment by clbarnes** [comment]
I've just released 1.0.0, which should address this (replacing colons with semicolons on windows). I don't have a windows machine handy, so if you use it, please let me know if it works!

**Comment by jasperoosthoek** [comment]
Just upgraded tempcase, removed my `path_to_cls` override and my tests run fine now :-). Thanks for the quick fix!

**Comment by clbarnes** [comment]
Grand, thanks for the report! Glad this is useful to someone.
